name: Auto Merge Request

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref }}
          title: 'Auto Merge Request'
          body: 'This is an automatically created merge request from ${{ github.ref }}'
          branch-suffix: timestamp 
